apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJibUZ6ZEdGeWEyOTJPbWRvY0Y5bVQwbHVjWGRFYmpWcWQwbGxaV1YyTkVWd1lsUlRZVEl3WldkYVdGVTBUV3B1TVhBPSJ9fSwiY3VycmVudENvbnRleHQiOiJkZXNrdG9wLWxpbnV4In0=
type: kubernetes.io/dockerconfigjson
